apiVersion: v2
name: pedido-app
description: Helm chart for Pedido App (Python backend + PostgreSQL subchart)
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
