image:
  repository: cristianb96/pedido-backend
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  FLASK_ENV: production
  LOG_LEVEL: info

postgresql:
  enabled: true
  global:
    postgresql:
      postgresqlDatabase: pedido_db
  postgresqlUsername: pedido_user
  postgresqlPassword: pedido_pass
  primary:
    persistence:
      enabled: true
      size: 8Gi
      accessModes: ["ReadWriteOnce"]

ingress:
  enabled: true
  hostname: pedido.example.com
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /api/

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

secrets:
  dbSecretName: pedido-db-credentials
