{{- if .Values.postgresql.postgresqlPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.dbSecretName }}
type: Opaque
stringData:
  postgresql-password: "{{ .Values.postgresql.postgresqlPassword }}"
{{- end }}
