apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedido-app-backend
  labels:
    app: pedido-app
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: pedido-app
      component: backend
  template:
    metadata:
      labels:
        app: pedido-app
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DATABASE_HOST
              value: "pedido-app-postgresql"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "{{ .Values.postgresql.global.postgresql.postgresqlDatabase }}"
            - name: DATABASE_USER
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: postgresql-password
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
